package com.le.ac.project.model;
// Generated 14-Mar-2017 15:29:15 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", catalog = "credit_score")
public class Address implements java.io.Serializable {

	private Integer addressId;
	private String postcode;
	private String addressType;
	private String addressOne;
	private String addressTwo;
	private String city;
	private String county;
	private String country;
	


	public Address() {
	}

	public Address(String postcode, String addressType, String addressOne, String city, String county, String country) {
		this.postcode = postcode;
		this.addressType = addressType;
		this.addressOne = addressOne;
		this.city = city;
		this.county = county;
		this.country = country;
	}

	public Address(String postcode, String addressType, String addressOne, String addressTwo, String city,
			String county, String country) {
		this.postcode = postcode;
		this.addressType = addressType;
		this.addressOne = addressOne;
		this.addressTwo = addressTwo;
		this.city = city;
		this.county = county;
		this.country = country;
		

	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "address_id", unique = true, nullable = false)
	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

	@Column(name = "postcode", nullable = false, length = 45)
	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	@Column(name = "address_type", nullable = false, length = 45)
	public String getAddressType() {
		return this.addressType;
	}

	public void setAddressType(String addressType) {
		this.addressType = addressType;
	}

	@Column(name = "address_one", nullable = false, length = 45)
	public String getAddressOne() {
		return this.addressOne;
	}
	
	public void setAddressOne(String addressOne) {
		this.addressOne = addressOne;
	}

	@Column(name = "address_two", length = 45)
	public String getAddressTwo() {
		return this.addressTwo;
	}

	public void setAddressTwo(String addressTwo) {
		this.addressTwo = addressTwo;
	}

	@Column(name = "city", nullable = false, length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "county", nullable = false, length = 45)
	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	@Column(name = "country", nullable = false, length = 45)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}





}
