package com.le.ac.project.model;
// Generated 14-Mar-2017 15:29:15 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * CreditReport generated by hbm2java
 */
@Entity
@Table(name = "credit_report_ml", catalog = "credit_score")
public class CreditReportMl implements java.io.Serializable {

	private Integer mlReportId;
	private Customer customer;
	private Date reportTime;
	private String reportStatus;
	private Integer isDeleted;
	private String accountStatus;
	private Double durationMonth;
	private String creditHistory;
	private String purpose;
	private Double creditAmount;
	private String savingAccount;
	private String employment;
	private Double installmentRatePecnt;
	private String sexAndStatus;
	private String otherDebtorsGuarantors;
	private Double presentResidenceTime;
	private String property;
	private Double age;
	private String otherInstalments;
	private String housing;
	private Double existingCreditsAtBank;
	private String job;
	private Integer numberDependents;
	private String telephone;
	private String foreignWorker;
	private Integer creditStatus;
	private Integer statusPrediction;
	private Double repayProbability;

	public CreditReportMl() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ml_report_id", unique = true, nullable = false)
	public Integer getMlReportId() {
		return mlReportId;
	}

	public void setMlReportId(Integer mlReportId) {
		this.mlReportId = mlReportId;
	}

	@ManyToOne
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "report_time", nullable = false, length = 19)
	public Date getReportTime() {
		return this.reportTime;
	}

	public void setReportTime(Date reportTime) {
		this.reportTime = reportTime;
	}

	@Column(name = "report_status", length = 45)
	public String getReportStatus() {
		return this.reportStatus;
	}

	public void setReportStatus(String reportStatus) {
		this.reportStatus = reportStatus;
	}

	@Column(name = "is_deleted", nullable = false)
	public Integer getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "account_status", length = 45)
	public String getAccountStatus() {
		return accountStatus;
	}

	public void setAccountStatus(String accountStatus) {
		this.accountStatus = accountStatus;
	}

	@Column(name = "duration_month")
	public Double getDurationMonth() {
		return durationMonth;
	}

	public void setDurationMonth(Double durationMonth) {
		this.durationMonth = durationMonth;
	}

	@Column(name = "credit_history", length = 45)
	public String getCreditHistory() {
		return creditHistory;
	}

	public void setCreditHistory(String creditHistory) {
		this.creditHistory = creditHistory;
	}

	@Column(name = "purpose", length = 45)
	public String getPurpose() {
		return purpose;
	}

	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}

	@Column(name = "credit_amount")
	public Double getCreditAmount() {
		return creditAmount;
	}

	public void setCreditAmount(Double creditAmount) {
		this.creditAmount = creditAmount;
	}

	@Column(name = "saving_account", length = 45)
	public String getSavingAccount() {
		return savingAccount;
	}

	public void setSavingAccount(String savingAccount) {
		this.savingAccount = savingAccount;
	}

	@Column(name = "employment", length = 45)
	public String getEmployment() {
		return employment;
	}

	public void setEmployment(String employment) {
		this.employment = employment;
	}

	@Column(name = "installment_rate_pecnt")
	public Double getInstallmentRatePecnt() {
		return installmentRatePecnt;
	}

	public void setInstallmentRatePecnt(Double installmentRatePecnt) {
		this.installmentRatePecnt = installmentRatePecnt;
	}

	@Column(name = "sex_and_status", length = 45)
	public String getSexAndStatus() {
		return sexAndStatus;
	}

	public void setSexAndStatus(String sexAndStatus) {
		this.sexAndStatus = sexAndStatus;
	}

	@Column(name = "other_debtors_guarantors", length = 45)
	public String getOtherDebtorsGuarantors() {
		return otherDebtorsGuarantors;
	}

	public void setOtherDebtorsGuarantors(String otherDebtorsGuarantors) {
		this.otherDebtorsGuarantors = otherDebtorsGuarantors;
	}

	@Column(name = "present_residence_time")
	public Double getPresentResidenceTime() {
		return presentResidenceTime;
	}

	public void setPresentResidenceTime(Double presentResidenceTime) {
		this.presentResidenceTime = presentResidenceTime;
	}

	@Column(name = "property", length = 45)
	public String getProperty() {
		return property;
	}

	public void setProperty(String property) {
		this.property = property;
	}

	@Column(name = "age")
	public Double getAge() {
		return age;
	}

	public void setAge(Double age) {
		this.age = age;
	}

	@Column(name = "other_instalments", length = 45)
	public String getOtherInstalments() {
		return otherInstalments;
	}

	public void setOtherInstalments(String otherInstalments) {
		this.otherInstalments = otherInstalments;
	}

	@Column(name = "housing", length = 45)
	public String getHousing() {
		return housing;
	}

	public void setHousing(String housing) {
		this.housing = housing;
	}

	@Column(name = "existing_credits_at_bank")
	public Double getExistingCreditsAtBank() {
		return existingCreditsAtBank;
	}

	public void setExistingCreditsAtBank(Double existingCreditsAtBank) {
		this.existingCreditsAtBank = existingCreditsAtBank;
	}

	@Column(name = "job", length = 45)
	public String getJob() {
		return job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	@Column(name = "number_dependents")
	public Integer getNumberDependents() {
		return numberDependents;
	}

	public void setNumberDependents(Integer numberDependents) {
		this.numberDependents = numberDependents;
	}

	@Column(name = "telephone", length = 45)
	public String getTelephone() {
		return telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "foreign_worker", length = 45)
	public String getForeignWorker() {
		return foreignWorker;
	}

	public void setForeignWorker(String foreignWorker) {
		this.foreignWorker = foreignWorker;
	}

	@Column(name = "credit_status")
	public Integer getCreditStatus() {
		return creditStatus;
	}

	public void setCreditStatus(Integer creditStatus) {
		this.creditStatus = creditStatus;
	}

	@Column(name = "status_prediction")
	public Integer getStatusPrediction() {
		return statusPrediction;
	}

	public void setStatusPrediction(Integer statusPrediction) {
		this.statusPrediction = statusPrediction;
	}

	@Column(name = "repay_probability")
	public Double getRepayProbability() {
		return repayProbability;
	}

	public void setRepayProbability(Double repayProbability) {
		this.repayProbability = repayProbability;
	}

}
