package com.le.ac.project.model;
// Generated 14-Mar-2017 15:29:15 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;


/**
 * CreditReport generated by hbm2java
 */
@Entity
@Table(name = "credit_report", catalog = "credit_score")
public class CreditReport implements java.io.Serializable {

	private Integer reportId;
	private Customer customer;
	private ReportSuggestion reportSuggestion;
	private Date reportTime;
	private String reportStatus;
	private Integer isDeleted;
	private String employmentStatus;
	private Integer employmentTime;
	private String residentialStatus;
	private Integer loanAmount;
	private Integer mortgage;
	private Integer annualIncomes;
	private Integer creditCardAmount;
	private Integer daysPastDue;
	private String isBankrupt;
	private Integer creditScore;
	private String currency;
	// yes: 1, no: 0, unknown: 2
	private Integer isHomeOwner;
	/*
	 * Non-primitive wrapper type Integer is required instead of primitive type
	 * int, because of exception: nested exception is
	 * org.hibernate.PropertyAccessException: Null value was assigned to a
	 * property of primitive type setter of... Hibernate will test or use the
	 * model(getter and setter) when query is invoked. Thus, when the data is
	 * null in database, primitive type int, which is not allow null data, is
	 * not safe.
	 */
	private Integer employmentStatusScore;
	private Integer employmentTimeScore;
	private Integer residentialScore;
	private Integer cardAmountScore;
	private Integer loanProportionScore;
	private Integer mortgageScore;
	private Integer pastDueScore;
	private Integer bankruptScore;
	private Double repayProbability;

	public CreditReport() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "report_id", unique = true, nullable = false)
	public Integer getReportId() {
		return this.reportId;
	}

	public void setReportId(Integer reportId) {
		this.reportId = reportId;
	}

	@ManyToOne
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "suggestion_id")
	public ReportSuggestion getReportSuggestion() {
		return this.reportSuggestion;
	}

	public void setReportSuggestion(ReportSuggestion reportSuggestion) {
		this.reportSuggestion = reportSuggestion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "report_time", nullable = false, length = 19)
	public Date getReportTime() {
		return this.reportTime;
	}

	public void setReportTime(Date reportTime) {
		this.reportTime = reportTime;
	}

	@Column(name = "report_status", length = 45)
	public String getReportStatus() {
		return this.reportStatus;
	}

	public void setReportStatus(String reportStatus) {
		this.reportStatus = reportStatus;
	}

	@Column(name = "is_deleted", nullable = false)
	public Integer getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "employment_status", length = 45)
	public String getEmploymentStatus() {
		return this.employmentStatus;
	}

	public void setEmploymentStatus(String employmentStatus) {
		this.employmentStatus = employmentStatus;
	}

	@Column(name = "employment_time")
	public Integer getEmploymentTime() {
		return employmentTime;
	}

	public void setEmploymentTime(Integer employmentTime) {
		this.employmentTime = employmentTime;
	}

	@Column(name = "residential_status", length = 45)
	public String getResidentialStatus() {
		return this.residentialStatus;
	}

	public void setResidentialStatus(String residentialStatus) {
		this.residentialStatus = residentialStatus;
	}

	@Column(name = "loan_amount")
	public Integer getLoanAmount() {
		return this.loanAmount;
	}

	public void setLoanAmount(Integer loanAmount) {
		this.loanAmount = loanAmount;
	}

	@Column(name = "mortgage")
	public Integer getMortgage() {
		return this.mortgage;
	}

	public void setMortgage(Integer mortgage) {
		this.mortgage = mortgage;
	}

	@Column(name = "annual_incomes")
	public Integer getAnnualIncomes() {
		return this.annualIncomes;
	}

	public void setAnnualIncomes(Integer annualIncomes) {
		this.annualIncomes = annualIncomes;
	}

	@Column(name = "credit_card_amount")
	public Integer getCreditCardAmount() {
		return creditCardAmount;
	}

	public void setCreditCardAmount(Integer creditCardAmount) {
		this.creditCardAmount = creditCardAmount;
	}

	@Column(name = "days_past_due", length = 11)
	public Integer getDaysPastDue() {
		return daysPastDue;
	}

	public void setDaysPastDue(Integer daysPastDue) {
		this.daysPastDue = daysPastDue;
	}

	@Column(name = "is_bankrupt")
	public String getIsBankrupt() {
		return isBankrupt;
	}

	public void setIsBankrupt(String isBankrupt) {
		this.isBankrupt = isBankrupt;
	}

	@Column(name = "credit_score")
	public Integer getCreditScore() {
		return creditScore;
	}

	public void setCreditScore(Integer creditScore) {
		this.creditScore = creditScore;
	}

	@Column(name = "currency", length = 45)
	public String getCurrency() {
		return currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "is_home_owner")
	public Integer getIsHomeOwner() {
		return isHomeOwner;
	}

	public void setIsHomeOwner(Integer isHomeOwner) {
		this.isHomeOwner = isHomeOwner;
	}

	@Column(name = "employment_status_score")
	public Integer getEmploymentStatusScore() {
		return employmentStatusScore;
	}

	public void setEmploymentStatusScore(Integer employmentStatusScore) {
		this.employmentStatusScore = employmentStatusScore;
	}

	@Column(name = "employment_time_score")
	public Integer getEmploymentTimeScore() {
		return employmentTimeScore;
	}

	public void setEmploymentTimeScore(Integer employmentTimeScore) {
		this.employmentTimeScore = employmentTimeScore;
	}

	@Column(name = "residential_score")
	public Integer getResidentialScore() {
		return residentialScore;
	}

	public void setResidentialScore(Integer residentialScore) {
		this.residentialScore = residentialScore;
	}

	@Column(name = "card_amount_score")
	public Integer getCardAmountScore() {
		return cardAmountScore;
	}

	public void setCardAmountScore(Integer cardAmountScore) {
		this.cardAmountScore = cardAmountScore;
	}

	@Column(name = "loan_proportion_score")
	public Integer getLoanProportionScore() {
		return loanProportionScore;
	}

	public void setLoanProportionScore(Integer loanProportionScore) {
		this.loanProportionScore = loanProportionScore;
	}

	@Column(name = "mortgage_score")
	public Integer getMortgageScore() {
		return mortgageScore;
	}

	public void setMortgageScore(Integer mortgageScore) {
		this.mortgageScore = mortgageScore;
	}

	@Column(name = "past_due_score")
	public Integer getPastDueScore() {
		return pastDueScore;
	}

	public void setPastDueScore(Integer pastDueScore) {
		this.pastDueScore = pastDueScore;
	}

	@Column(name = "bankrupt_score", nullable = true)
	public Integer getBankruptScore() {
		return bankruptScore;
	}

	public void setBankruptScore(Integer bankruptScore) {
		this.bankruptScore = bankruptScore;
	}

	@Column(name = "repay_probability")
	public Double getRepayProbability() {
		return repayProbability;
	}

	public void setRepayProbability(Double repayProbability) {
		this.repayProbability = repayProbability;
	}

	
	
}
