package com.le.ac.project.model;
// Generated 14-Mar-2017 15:29:15 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CustomerLender generated by hbm2java
 */
@Entity
@Table(name = "customer_lender", catalog = "credit_score")
public class CustomerLender implements java.io.Serializable {

	private Integer customerLenderId;
	private Lender lender;
	private Customer customer;

	public CustomerLender() {
	}

	public CustomerLender(Lender lender, Customer customer) {
		this.lender = lender;
		this.customer = customer;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "customer_lender_id", unique = true, nullable = false)
	public Integer getCustomerLenderId() {
		return this.customerLenderId;
	}

	public void setCustomerLenderId(Integer customerLenderId) {
		this.customerLenderId = customerLenderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lender_id", nullable = false)
	public Lender getLender() {
		return this.lender;
	}

	public void setLender(Lender lender) {
		this.lender = lender;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

}
