package com.le.ac.project.model;
// Generated 14-Mar-2017 15:29:15 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Lender generated by hbm2java
 */
@Entity
@Table(name = "lender", catalog = "credit_score")
public class Lender implements java.io.Serializable {

	private Integer lenderId;
	private Integer roleId;
	private Address address;
	private String type;
	private String name;
	private String tel;
	private Integer isDeleted;
	private Date authorizedTime;
	private String email;
	private String password;
	private String principal;
	private Date applyingTime;
	private Date updateTime;
	private Integer model;
	private String criteria;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "authorized_time", length = 19)
	public Date getAuthorizedTime() {
		return authorizedTime;
	}

	public void setAuthorizedTime(Date authorizedTime) {
		this.authorizedTime = authorizedTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "applying_time", length = 19)
	public Date getApplyingTime() {
		return applyingTime;
	}

	public void setApplyingTime(Date applyingTime) {
		this.applyingTime = applyingTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "lender_id", unique = true, nullable = false)
	public Integer getLenderId() {
		return this.lenderId;
	}

	public void setLenderId(Integer lenderId) {
		this.lenderId = lenderId;
	}

	
	@Column(name = "role_id", nullable = false)
	public Integer getRoleId() {
		return roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}


	@ManyToOne
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "address_id")
	public Address getAddress() {
		return this.address;
	}



	public void setAddress(Address address) {
		this.address = address;
	}

	@Column(name = "type", nullable = false, length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "tel", length = 45)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "is_deleted", nullable = false, length = 45)
	public Integer getIsDeleted() {
		return isDeleted;
	}

	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	
	@Column(name = "email", nullable = false, length = 45)
	public String getEmail() {
		return email;
	}

	

	public void setEmail(String email) {
		this.email = email;
	}
	
	@Column(name = "principal", length = 45)
	public String getPrincipal() {
		return principal;
	}

	public void setPrincipal(String principal) {
		this.principal = principal;
	}

	@Column(name = "model", length = 11)
	public Integer getModel() {
		return model;
	}

	public void setModel(Integer model) {
		this.model = model;
	}

	@Column(name = "criteria", length = 11)
	public String getCriteria() {
		return criteria;
	}

	public void setCriteria(String criteria) {
		this.criteria = criteria;
	}
	
	
}
