package com.le.ac.project.model;
// Generated 14-Mar-2017 15:29:15 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Privilege generated by hbm2java
 */
@Entity
@Table(name = "privilege", catalog = "credit_score")
public class Privilege implements java.io.Serializable {
	
	@Id
	private Integer privilegeId;
	@Column
	private String privilegeName;
	@Column
	private String privilegeUrl;
	@Column
	private String privilegeStatus;
	@Column
	private Set<RolePrivilege> rolePrivileges = new HashSet<RolePrivilege>(0);

	public Privilege() {
	}

	public Privilege(String privilegeName) {
		this.privilegeName = privilegeName;
	}

	public Privilege(String privilegeName, String privilegeUrl, String privilegeStatus,
			Set<RolePrivilege> rolePrivileges) {
		this.privilegeName = privilegeName;
		this.privilegeUrl = privilegeUrl;
		this.privilegeStatus = privilegeStatus;
		this.rolePrivileges = rolePrivileges;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "privilege_id", unique = true, nullable = false)
	public Integer getPrivilegeId() {
		return this.privilegeId;
	}

	public void setPrivilegeId(Integer privilegeId) {
		this.privilegeId = privilegeId;
	}

	@Column(name = "privilege_name", nullable = false, length = 45)
	public String getPrivilegeName() {
		return this.privilegeName;
	}

	public void setPrivilegeName(String privilegeName) {
		this.privilegeName = privilegeName;
	}

	@Column(name = "privilege_url", length = 45)
	public String getPrivilegeUrl() {
		return this.privilegeUrl;
	}

	public void setPrivilegeUrl(String privilegeUrl) {
		this.privilegeUrl = privilegeUrl;
	}

	@Column(name = "privilege_status", length = 45)
	public String getPrivilegeStatus() {
		return this.privilegeStatus;
	}

	public void setPrivilegeStatus(String privilegeStatus) {
		this.privilegeStatus = privilegeStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "privilege")
	public Set<RolePrivilege> getRolePrivileges() {
		return this.rolePrivileges;
	}

	public void setRolePrivileges(Set<RolePrivilege> rolePrivileges) {
		this.rolePrivileges = rolePrivileges;
	}

}
