package com.le.ac.project.model;
// Generated 14-Mar-2017 15:29:15 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ReportSuggestion generated by hbm2java
 */
@Entity
@Table(name = "report_suggestion", catalog = "credit_score")
public class ReportSuggestion implements java.io.Serializable {

	private Integer reportSuggestionId;
	private Suggestion suggestion;
	private Integer reportId;
	private Set<CreditReport> creditReports = new HashSet<CreditReport>(0);

	public ReportSuggestion() {
	}

	public ReportSuggestion(Suggestion suggestion, Integer reportId) {
		this.suggestion = suggestion;
		this.reportId = reportId;
	}

	public ReportSuggestion(Suggestion suggestion, Integer reportId, Set<CreditReport> creditReports) {
		this.suggestion = suggestion;
		this.reportId = reportId;
		this.creditReports = creditReports;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "report_suggestion_id", unique = true, nullable = false)
	public Integer getReportSuggestionId() {
		return this.reportSuggestionId;
	}

	public void setReportSuggestionId(Integer reportSuggestionId) {
		this.reportSuggestionId = reportSuggestionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "suggestion_id", nullable = false)
	public Suggestion getSuggestion() {
		return this.suggestion;
	}

	public void setSuggestion(Suggestion suggestion) {
		this.suggestion = suggestion;
	}

	@Column(name = "report_id", nullable = false)
	public Integer getReportId() {
		return this.reportId;
	}

	public void setReportId(Integer reportId) {
		this.reportId = reportId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reportSuggestion")
	public Set<CreditReport> getCreditReports() {
		return this.creditReports;
	}

	public void setCreditReports(Set<CreditReport> creditReports) {
		this.creditReports = creditReports;
	}

}
