package com.le.ac.project.model;
// Generated 14-Mar-2017 15:29:15 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * RolePrivilege generated by hbm2java
 */
@Entity
@Table(name = "role_privilege", catalog = "credit_score")
public class RolePrivilege implements java.io.Serializable {
	
	
	private Integer rolePrivilegeId;
	
	private Privilege privilege;
	
	private Integer roleId;
	
	

	

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "role_privilege_id", unique = true, nullable = false)
	public Integer getRolePrivilegeId() {
		return this.rolePrivilegeId;
	}

	public void setRolePrivilegeId(Integer rolePrivilegeId) {
		this.rolePrivilegeId = rolePrivilegeId;
	}

	@ManyToOne
	@JoinColumn(name="privilegeId")
	@Fetch(FetchMode.SELECT)
	public Privilege getPrivilege() {
		return this.privilege;
	}

	public void setPrivilege(Privilege privilege) {
		this.privilege = privilege;
	}

	@Column(name = "role_id", nullable = false)
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}



}
